import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>The YakShop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="./">The YakShop!</a>
        </h1>

        <p className={styles.description}>
          Get started by choosing a page
        </p>

        <div className={styles.grid}>
          <a href="./herd/13" className={styles.card}>
            <h2>Herd &rarr;</h2>
            <p>Get herd data on a given day.</p>
          </a>

          <a href="./stock/13" className={styles.card}>
            <h2>Stock &rarr;</h2>
            <p>Know the stock on a given day</p>
          </a>

          <a href="./order" className={styles.card}>
            <h2>Order &rarr;</h2>
            <p>Order skin and milk</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="./">
          The YakShop
        </a>
      </footer>
    </div>
  )
}

export default Home
